plugins {
    id 'songify.android.application'
}

dependencies {
    // DO NOT ADD ANY MORE DEPENDENCIES!!!
    implementation libs.core.splashscreen
    implementation libs.material
    implementation projects.feature.login.internal
    implementation projects.library.bottomNavigation.public
    implementation projects.library.circuit.public
    implementation projects.library.theme.public
    // DO NOT ADD ANY MORE DEPENDENCIES!!!

    // Which app do we load?
    implementation projects.feature.detail.internal
    implementation projects.feature.home.internal
    implementation projects.feature.nowplaying.internal
    implementation projects.feature.premium.internal
    implementation projects.feature.search.internal
    implementation projects.library.detail.internal
    implementation projects.library.home.internal
    implementation projects.library.premium.internal
    implementation projects.library.search.internal
    implementation projects.library.spotify.internal
}
