package com.songify.feature.spotify.internal

import com.songify.library.posts.Community
import com.songify.library.posts.Person
import com.songify.library.posts.Post
import com.songify.library.posts.PostAggregates
import com.songify.library.posts.PostView
import com.songify.library.posts.SubscribedType

val samplePost = Post(
    id = 135129,
    name = "In a socialist world, would jobs still have probation periods ?",
    url = null,
    body = "At least for me, finding work is hard and knowing i could be easily fired for the first 6 months is stressful .",
    creator_id = 33401,
    community_id = 14681,
    removed = false,
    locked = false,
    published = "2022-01-01T09:53:46.904077",
    updated = null,
    deleted = false,
    nsfw = false,
    featured_local = false,
    featured_community = false,
    embed_title = null,
    embed_description = null,
    embed_video_url = null,
    thumbnail_url = null,
    language_id = 0,
    ap_id = "https://lemmy.ml/post/135129", local = true,
)

val sampleLinkPost = Post(
    id = 135130,
    name = "Omicron is not mild and is crushing health care systems worldwide, WHO warns",
    url = "https://arstechnica.com/science/2022/01/omicron-is-not-mild-and-is-crushing-health-care-systems-worldwide-who-warns/",
    body = "At least for me, finding work is hard and knowing i could be easily fired for the first 6 months is stressful .",
    creator_id = 33401,
    community_id = 14681,
    removed = false,
    locked = true,
    published = "2022-01-01T09:53:46.904077",
    updated = null,
    deleted = false,
    nsfw = false,
    featured_local = false,
    featured_community = false,
    embed_title = null,
    embed_description = "Just like previous variants, omicron is hospitalizing people, and it is killing people.",
    embed_video_url = null,
    thumbnail_url = "https://lemmy.ml/pictrs/image/08967513-afcb-495a-9116-562a0cb1a44f.jpeg",
    ap_id = "https://lemmy.ml/post/135129", local = true,
    language_id = 0,
)

val sampleLinkNoThumbnailPost = Post(
    id = 135130,
    name = "Omicron is not mild and is crushing health care systems worldwide, WHO warns",
    url = "https://arstechnica.com/science/2022/01/omicron-is-not-mild-and-is-crushing-health-care-systems-worldwide-who-warns/",
    body = "At least for me, finding work is hard and knowing i could be easily fired for the first 6 months is stressful .",
    creator_id = 33401,
    community_id = 14681,
    removed = false,
    locked = false,
    published = "2022-01-01T09:53:46.904077",
    updated = null,
    deleted = false,
    nsfw = false,
    featured_local = false,
    featured_community = false,
    embed_title = null,
    embed_description = "Just like previous variants, omicron is hospitalizing people, and it is killing people.",
    embed_video_url = null,
    thumbnail_url = null,
    ap_id = "https://lemmy.ml/post/135129", local = true,
    language_id = 0,
)

val sampleImagePost = Post(
    id = 135130,
    name = "This is a large image",
    url = "https://lemmy.ml/pictrs/image/08967513-afcb-495a-9116-562a0cb1a44f.jpeg",
    body = "The body of an image post",
    creator_id = 33401,
    community_id = 14681,
    removed = false,
    locked = false,
    published = "2022-01-01T09:53:46.904077",
    updated = null,
    deleted = false,
    nsfw = false,
    featured_local = false,
    featured_community = false,
    embed_title = null,
    embed_description = "Just like previous variants, omicron is hospitalizing people, and it is killing people.",
    embed_video_url = null,
    thumbnail_url = "https://lemmy.ml/pictrs/image/08967513-afcb-495a-9116-562a0cb1a44f.jpeg",
    ap_id = "https://lemmy.ml/post/135129", local = true,
    language_id = 0,
)

val sampleMarkdownPost = Post(
    id = 135130,
    name = "This is a markdown post",
    url = null,
    body = "# Heading 1  1. First Item  2. Second Item  3. Third item  And a `code` block",
    creator_id = 33401,
    community_id = 14681,
    removed = false,
    locked = false,
    published = "2022-01-01T09:53:46.904077",
    updated = null,
    deleted = false,
    nsfw = false,
    featured_local = false,
    featured_community = false,
    embed_title = null,
    embed_description = null,
    embed_video_url = null,
    thumbnail_url = null,
    language_id = 0,
    ap_id = "https://lemmy.ml/post/135129", local = true,
)

val samplePerson = Person(
    id = 33401,
    name = "homeless",
    display_name = "No longer Homeless",
    avatar = "https://lemmy.ml/pictrs/image/LqURxPzFNW.jpg",
    banned = false,
    published = "2021-08-08T01:47:44.437708",
    updated = "2021-10-11T07:14:53.548707",
    actor_id = "https://lemmy.ml/u/homeless",
    bio = "This is my bio.\n\nI like trucks, trains, and geese. This is *one* longer line " +
            "that I have in here. But I'm not sure blah blah blah\n\nI have " +
            "**tres ojos**.",
    local = true,
    banner = null,
    deleted = false,
    matrix_user_id = null,
    admin = false,
    bot_account = false,
    ban_expires = null,
    instance_id = 0,
)

val samplePerson2 = Person(
    id = 33403,
    name = "gary_host_laptop",
    display_name = null,
    avatar = "https://lemmy.ml/pictrs/image/kykidJ1ssM.jpg",
    banned = false,
    published = "2021-08-08T01:47:44.437708",
    updated = "2021-10-11T07:14:53.548707",
    actor_id = "https://lemmy.ml/u/homeless",
    bio = null,
    local = true,
    banner = null,
    deleted = false,
    matrix_user_id = null,
    admin = false,
    bot_account = false,
    ban_expires = null,
    instance_id = 0,
)

val sampleCommunity = Community(
    id = 14681,
    name = "socialism",
    title = "Socialism",
    description = "This is the r/socialism community",
    removed = false,
    published = "2019-04-30T13:28:35.965035",
    updated = "2021-01-25T16:27:15.804739",
    deleted = false,
    nsfw = false,
    actor_id = "https://lemmy.ml/c/socialism",
    local = true,
    icon = null,
    banner = "https://lemmy.ml/pictrs/image/386rk5OYWS.jpg",
    instance_id = 0,
    hidden = false,
    posting_restricted_to_mods = false,
)

val samplePostAggregates = PostAggregates(
    id = 56195,
    post_id = 135129,
    numComments = 4,
    score = 8,
    upvotes = 8,
    downvotes = 0,
    featured_local = false,
    featured_community = false,
    newest_comment_time_necro = "2022-01-02T04:02:44.592929",
    newest_comment_time = "2022-01-02T04:02:44.592929",
    published = "2022-01-02T04:02:44.592929",
//    hot_rank = 5,
//    hot_rank_active = 6,
)

val samplePostView = PostView(
    post = samplePost,
    creator = samplePerson,
    community = sampleCommunity,
    creator_banned_from_community = false,
    counts = samplePostAggregates,
    subscribed = SubscribedType.NotSubscribed,
    saved = false,
    read = false,
    creator_blocked = false,
    my_vote = null,
    unread_comments = 0,
)

val sampleLinkPostView = PostView(
    post = sampleLinkPost,
    creator = samplePerson,
    community = sampleCommunity,
    creator_banned_from_community = false,
    counts = samplePostAggregates,
    subscribed = SubscribedType.NotSubscribed,
    saved = false,
    read = false,
    creator_blocked = false,
    my_vote = null,
    unread_comments = 0,
)

val sampleLinkNoThumbnailPostView = PostView(
    post = sampleLinkNoThumbnailPost,
    creator = samplePerson,
    community = sampleCommunity,
    creator_banned_from_community = false,
    counts = samplePostAggregates,
    subscribed = SubscribedType.NotSubscribed,
    saved = false,
    read = false,
    creator_blocked = false,
    my_vote = null,
    unread_comments = 0,
)

val sampleImagePostView = PostView(
    post = sampleImagePost,
    creator = samplePerson,
    community = sampleCommunity,
    creator_banned_from_community = false,
    counts = samplePostAggregates,
    subscribed = SubscribedType.NotSubscribed,
    saved = false,
    read = false,
    creator_blocked = false,
    my_vote = null,
    unread_comments = 0,
)

val sampleMarkdownPostView = PostView(
    post = sampleMarkdownPost,
    creator = samplePerson,
    community = sampleCommunity,
    creator_banned_from_community = false,
    counts = samplePostAggregates,
    subscribed = SubscribedType.NotSubscribed,
    saved = false,
    read = false,
    creator_blocked = false,
    my_vote = null,
    unread_comments = 0,
)
